### PR TITLE
Codecov

### LINKED ISSUE #5: codecov.io
Need to enable code coverage and I'd like to try out codecov.io to see how it compares with coveralls

### PR DESCRIPTION
**Pull request by glibsm**
Seeing if the super basic setup is enough. 

Fixes #5

### CODE REVIEW

**Comment by breerly** [comment]
I *believe* you need a `.codecov.yaml` file... check out their docs for Go

**Comment by glibsm** [comment]
I'm just trying to follow https://github.com/codecov/example-go to start with

**Comment by breerly** [comment]
neat!

**Comment by breerly** [comment]
We should set the threshold to 95% so the build fails if we fall below that number.

**Pull request merged**
